package org.acherie.demo.dao.generator;

import java.util.List;
import org.acherie.demo.model.generator.CountryLanguage;
import org.acherie.demo.model.generator.CountryLanguageExample;
import org.acherie.demo.model.generator.CountryLanguageKey;
import org.apache.ibatis.annotations.Param;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    long countByExample(CountryLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int deleteByExample(CountryLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int deleteByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int insertSelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    List<CountryLanguage> selectByExample(CountryLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    CountryLanguage selectByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") CountryLanguage record, @Param("example") CountryLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int updateByExample(@Param("record") CountryLanguage record, @Param("example") CountryLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int updateByPrimaryKeySelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Sat Oct 08 08:10:25 CST 2016
     */
    int updateByPrimaryKey(CountryLanguage record);
}